# VirtualHost minimaliste avec logs vers stdout/stderr
<VirtualHost *:80>
    ServerAdmin admin@local
    DocumentRoot /var/www/html/dvwa

    <Directory /var/www/html/dvwa>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    # Logs 12-Factor: vers les FDs standards
    ErrorLog /proc/self/fd/2
    CustomLog /proc/self/fd/1 combined
</VirtualHost>
